In [ ]:
# 📖 Scenario: Retail Sales Data Encoding
# Imagine you are working as a data analyst for a retail company. The company wants
# to build a machine learning model to predict sales performance based on product type
# and region. However, the dataset contains categorical variables (like Product and Region)
# that machine learning algorithms cannot directly process — they need numerical inputs.

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [3]:
data = pd.DataFrame({
    'Product' : ['Shoes' , 'Shirt' , 'Shoes' , 'Watch'],
    'Region' : ['North' , 'South' , 'East' , 'West'],
    'Sales' : [200,150,300,400]
})

data

  Product Region  Sales
0   Shoes  North    200
1   Shirt  South    150
2   Shoes   East    300
3   Watch   West    400

In [4]:
le = LabelEncoder()
data['Product_encoded'] = le.fit_transform(data['Product'])

In [6]:
ohe = OneHotEncoder(sparse_output = False)
region_encoded = ohe.fit_transform(data[['Region']])
region_df = pd.DataFrame(region_encoded , columns = ohe.get_feature_names_out(['Region']))

In [8]:
data = pd.concat([data , region_df] , axis = 1)
data

,Product,Region,Sales,Product_encoded,Region_East,Region_North,Region_South,Region_West,Region_East,Region_North,Region_South,Region_West
0,Shoes,North,200,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,Shirt,South,150,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,Shoes,East,300,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,Watch,West,400,2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [9]:
#  Scenario: Healthcare Patient Records Encoding
# Imagine you are working as a data scientist in a hospital. The hospital wants to build a machine
#  learning model to predict patient recovery time based on demographic and treatment details.
#   The dataset contains categorical variables (like Treatment Type and Hospital Wing) that must be converted into numeric form before modeling.
# Business Context
# - Treatment Type: Different medical procedures (Surgery, Therapy, Medication).
# - Hospital Wing: Location where the patient is admitted (East, West, North, South).
# - Recovery Days: Numeric values representing how many days the patient took to recover.
# The challenge:
# Machine learning models cannot directly interpret text categories, so you need to encode categorical
#  features into numbers.

In [10]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [11]:
data = pd.DataFrame({
    'Treatment_Type' : ['Surgery' , 'Therapy' , 'Medication' , 'Therapy' , 'Surgery'],
    'Wings' : ['North' , 'South' , 'East' , 'West' , 'North'],
    'Recovery_Days' : [20,15,3,40,5]
})

data

  Treatment_Type  Wings  Recovery_Days
0        Surgery  North             20
1        Therapy  South             15
2     Medication   East              3
3        Therapy   West             40
4        Surgery  North              5

In [16]:
le = LabelEncoder()
data['Type_encoded'] = le.fit_transform(data['Treatment_Type'])
data['Type_encoded']

0    1
1    2
2    0
3    2
4    1
Name: Type_encoded, dtype: int64

In [13]:
ohe = OneHotEncoder(sparse_output = False)
wings_encoded = ohe.fit_transform(data[['Wings']])
wings_df = pd.DataFrame(
    wings_encoded ,
    columns = ohe.get_feature_names_out(['Wings'])
)

In [14]:
data = pd.concat([data , wings_df] , axis = 1)

In [15]:
data

,Treatment_Type,Wings,Recovery_Days,Type_encoded,Wings_East,Wings_North,Wings_South,Wings_West
0,Surgery,North,20,1,0.0,1.0,0.0,0.0
1,Therapy,South,15,2,0.0,0.0,1.0,0.0
2,Medication,East,3,0,1.0,0.0,0.0,0.0
3,Therapy,West,40,2,0.0,0.0,0.0,1.0
4,Surgery,North,5,1,0.0,1.0,0.0,0.0

In [ ]:
# PIPELINE

In [17]:
# Scenario: Student Exam Pass Prediction 🎓

# A university wants to predict whether a student will pass or fail an exam based
#  on their personal and academic information. The dataset contains the following features:

# age → Age of the student (numeric)
# hours_study → Number of hours the student studies per day (numeric)
# gender → Male or Female (categorical)
# school → School type (Government or Private) (categorical)
# pass_exam → Target variable (1 = Pass, 0 = Fail)

# The data science team decides to build a machine learning pipeline that:

# Standardizes numeric features (age, hours_study) so they are on the same scale.
# Converts categorical features (gender, school) into numerical format using One-Hot Encoding.
# Combines preprocessing and model training into a single pipeline.
# Uses Logistic Regression to predict whether a student will pass.

In [18]:
import pandas as pd

In [19]:
data = {
    'age' : [18,19,18,20,13] ,
    'hours_study' : [2,5,1,6,4] , 
    'gender' : ['Male' , 'Female' , 'Male' , 'Male' , 'Female'] , 
    'school' : ['Government' , 'Private' , 'Private' , 'Government' , 'Private'] , 
    'pass_exam' : [0,1,0,1,1]
}

df = pd.DataFrame(data)

In [20]:
df

   age  hours_study  gender      school  pass_exam
0   18            2    Male  Government          0
1   19            5  Female     Private          1
2   18            1    Male     Private          0
3   20            6    Male  Government          1
4   13            4  Female     Private          1

In [26]:
# features and target

X = df[['age' , 'hours_study' , 'gender' , 'school']]
Y = df['pass_exam']

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [23]:
numeric_features = ['age' , 'hours_study']
categorical_features = ['gender' , 'school']

# ColumnTransformer allows you to apply different preprocessing methods to different columns in one step
preprocessor = ColumnTransformer(
    # A transformer is any object that modifies or preprocesses data before it goes into a model.
    transformers = [
        ('num' , StandardScaler(), numeric_features),
        ('cat' , OneHotEncoder() , categorical_features)
    ]
)

In [24]:
# A Pipeline connects multiple steps into one single workflow.

pipeline = Pipeline(steps = [
    ('preprocessor' , preprocessor) , 
    ('classifier' , LogisticRegression())
])

In [25]:
pipeline.fit(X,Y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'hours_study']),
                                                 ('cat', OneHotEncoder(),
                                                  ['gender', 'school'])])),
                ('classifier', LogisticRegression())])

In [27]:
new_student = pd.DataFrame({
    'age' : [19],
    'hours_study' : [3] ,
    'gender' : ['Female'] , 
    'school' : ['Government']
})

prediction = pipeline.predict(new_student)
print("Prediction : " , prediction)

Prediction :  [1]

In [38]:
# 📖 Scenario: Employee Attrition Prediction 💼
# A company wants to predict whether an employee is likely to stay or leave based on their personal and workplace information. The dataset contains the following features:
# - age → Age of the employee (numeric)
# - years_experience → Number of years of work experience (numeric)
# - department → Department (HR, IT, Sales) (categorical)
# - education → Education level (Graduate, Postgraduate) (categorical)
# - attrition → Target variable (1 = Leaves, 0 = Stays)

# The data science team decides to build a machine learning pipeline that:
# - Standardizes numeric features (age, years_experience).
# - Converts categorical features (department, education) into numerical format using One-Hot Encoding.
# - Combines preprocessing and model training into a single pipeline.
# - Uses Logistic Regression to predict employee attrition.

In [39]:
import pandas as pd


data = {
    'age' : [18,19,18,20,13] ,
    'years_experience' : [2,5,1,6,4] , 
    'department' : ['HR' , 'IT' , 'Sales' , 'Sales' , 'Hr'] , 
    'education' : ['Graduate' , 'Postgraduate' , 'Postgraduate' , 'Graduate' , 'PostGraduate'] , 
    'attrition' : [0,1,0,1,1]
}

df = pd.DataFrame(data)

In [40]:
df

   age  years_experience department     education  attrition
0   18                 2         HR      Graduate          0
1   19                 5         IT  Postgraduate          1
2   18                 1      Sales  Postgraduate          0
3   20                 6      Sales      Graduate          1
4   13                 4         Hr  PostGraduate          1

In [41]:
X = df[['age' , 'years_experience' , 'department' , 'education']]
Y = df['attrition']

In [42]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [43]:
numeric_features = ['age' , 'years_experience']
categorical_features = ['department' , 'education']

preprocessor = ColumnTransformer(
    transformers = [
        ('num' , StandardScaler(), numeric_features),
        ('cat' , OneHotEncoder() , categorical_features)
    ]
)



pipeline = Pipeline(steps = [
    ('preprocessor' , preprocessor) , 
    ('classifier' , LogisticRegression())
])

In [44]:
pipeline.fit(X,Y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'years_experience']),
                                                 ('cat', OneHotEncoder(),
                                                  ['department',
                                                   'education'])])),
                ('classifier', LogisticRegression())])

In [45]:
new_data = pd.DataFrame({
    'age' : [23] ,
    'years_experience' : [8] , 
    'department' : ['HR'] , 
    'education' : ['Postgraduate'] 
})

prediction = pipeline.predict(new_data)
print("Prediction : " , prediction)

Prediction :  [1]