In [2]:
# Scenario: Employee Training & Satisfaction Survey
# A company conducts a survey to understand how employee education level and job satisfaction affect performance.
# They collect data such as:
# - Education: High School, Bachelor, Master, PhD
# - Satisfaction: Poor, Average, Good, Excellent
# Since these categories have a natural order (e.g., PhD is higher than Bachelor, Excellent is better
#  than Good), the company decides to use Ordinal Encoding to convert them into numbers that respect 
#  this ranking.
# They define custom ordering:
# - Education → High School (0), Bachelor (1), Master (2), PhD (3)
# - Satisfaction → Poor (0), Average (1), Good (2), Excellent (3)
# They also compare this with a manual dictionary mapping to ensure consistency.

# Questions for Learners
# Part A: Why is it important to use Ordinal Encoding instead of simple Label Encoding for ordered 
# categories like education level?
# Part B: If the company encoded “PhD = 0” and “High School = 3,” what problem might arise in 
# interpreting the model?
# Part C: How does Ordinal Encoding differ from One-Hot Encoding in representing categorical data?
# Part D (Applied): Suppose the company adds a new satisfaction level “Outstanding.” How should they 
# update their encoding scheme to keep the order meaningful?

In [3]:
import pandas as pd
# It converts categorical data into numeric values based on a defined order (ranking).
from sklearn.preprocessing import OrdinalEncoder

In [4]:
data = pd.DataFrame({
    'Education' : ['Bachelor' , 'PhD' , 'Master' , 'High School'],
    'Satisfaction' : ['Good' , 'Excellent' , 'Poor' , 'Average']
})

In [5]:
data

     Education Satisfaction
0     Bachelor         Good
1          PhD    Excellent
2       Master         Poor
3  High School      Average

In [6]:
education_order = [['High School' , 'Bachelor' , 'Master' , 'PhD']]
satisfaction_order = [['Poor' , 'Average' , 'Good' , 'Excellent']]

In [9]:
edu_encoder = OrdinalEncoder(categories = education_order)
data['Education_Encoded'] = edu_encoder.fit_transform(data[['Education']])

sat_encoder = OrdinalEncoder(categories = satisfaction_order)
data['Satisfaction_Encoded'] = sat_encoder.fit_transform(data[['Satisfaction']])

In [10]:
# Gives full control over ranking
# Ensures correct order (not alphabetical)
# Same result as OrdinalEncoder but done manually


education_map = {
    'High School' : 0 , 'Bachelor' : 1 , 
    'Master' : 2 , 'PhD' : 3
}


satisfaction_map = {
    'Poor' : 0 , 'Average' : 1 , 
    'Good' : 2 , 'Excellent' : 3
}

In [12]:
data['Education_Manual'] = data['Education'].map(education_map)
data['Satisfaction_Manual'] = data['Satisfaction'].map(satisfaction_map)

In [14]:
print("Manual Mapping Comparison:\n")
data

Manual Mapping Comparison:

,Education,Satisfaction,Education_Encoded,Satisfaction_Encoded,Education_Manual,Satisfaction_Manual
0,Bachelor,Good,1.0,2.0,1,2
1,PhD,Excellent,3.0,3.0,3,3
2,Master,Poor,2.0,0.0,2,0
3,High School,Average,0.0,1.0,0,1

In [15]:
# Scenario: Patient Health Monitoring
# A hospital wants to analyze patient records to understand how disease severity and recovery 
# satisfaction affect treatment outcomes.
# They collect data such as:
# - Disease Severity: Mild, Moderate, Severe, Critical
# - Recovery Satisfaction: Poor, Average, Good, Excellent
# Since these categories have a natural order (e.g., Critical is worse than Mild, Excellent is 
# better than Poor), the hospital uses Ordinal Encoding to convert them into numbers that respect this
#  ranking.
# They define custom ordering:
# - Disease Severity → Mild (0), Moderate (1), Severe (2), Critical (3)
# - Recovery Satisfaction → Poor (0), Average (1), Good (2), Excellent (3)
# They also compare this with a manual dictionary mapping to ensure consistency.

In [16]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [17]:
data = pd.DataFrame({
    'Disease' : ['Mild' , 'Moderate' , 'Severe' , 'Critical'],
    'Satisfaction' : ['Good' , 'Excellent' , 'Poor' , 'Average']
})

In [18]:
data

    Disease Satisfaction
0      Mild         Good
1  Moderate    Excellent
2    Severe         Poor
3  Critical      Average

In [19]:
disease_order = [['Mild' , 'Moderate' , 'Severe' , 'Critical']]
satisfaction_order = [['Poor' , 'Average' , 'Good' , 'Excellent']]

dise_encoder = OrdinalEncoder(categories = disease_order)
data['Disease_Encoded'] = dise_encoder.fit_transform(data[['Disease']])

sat_encoder = OrdinalEncoder(categories = satisfaction_order)
data['Satisfaction_Encoded'] = sat_encoder.fit_transform(data[['Satisfaction']])

In [20]:
disease_map = {
    'Mild' : 0 , 'Moderate' : 1 , 
    'Severe' : 2 , 'Critical' : 3
}


satisfaction_map = {
    'Poor' : 0 , 'Average' : 1 , 
    'Good' : 2 , 'Excellent' : 3
}

In [21]:
data['Disease_Manual'] = data['Disease'].map(disease_map)
data['Satisfaction_Manual'] = data['Satisfaction'].map(satisfaction_map)

In [22]:
print("Manual Mapping Comparison:\n")
data

Manual Mapping Comparison:

,Disease,Satisfaction,Disease_Encoded,Satisfaction_Encoded,Disease_Manual,Satisfaction_Manual
0,Mild,Good,0.0,2.0,0,2
1,Moderate,Excellent,1.0,3.0,1,3
2,Severe,Poor,2.0,0.0,2,0
3,Critical,Average,3.0,1.0,3,1