In [86]:
# Capstone Project 3 
# Smart Marketing Prediction System (ML Pipeline Project)

# Scenario

# A fast-growing e-commerce company called ShopEasy is struggling with inefficient marketing campaigns.
# Every day thousands of users visit their website. The marketing team spends a large amount of money showing ads, discounts, and promotional emails, but they don't know which customers are actually likely to buy something.
# Currently:

# Many customers browse but never purchase
# Marketing money is wasted on the wrong users
# The company wants to predict purchase probability
# The data science team has been asked to build a machine learning system that predicts whether a customer will purchase a product during a session.

# If the system predicts high probability of purchase, the system will:
# show personalized product recommendations
# offer targeted discounts
# prioritize marketing campaigns
# If the system predicts low probability, the company will avoid spending marketing resources.
# However, the dataset contains both numerical and categorical features, so the data science team must design a complete ML pipeline.
# Dataset is available in DatasetCapstoneProject3 in the github repo link https://github.com/himanshusar123/Datasets

# Business Objective

# Build a machine learning model that predicts whether a user will purchase (1) or not purchase (0) during a website session.
# The model must be implemented using scikit-learn pipelines, including:

# Encoding techniques
# Feature preprocessing
# Model training
# Model selection
# Hyperparameter tuning

In [87]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , classification_report
from sklearn.linear_model import LogisticRegression

In [88]:
df = pd.read_excel("DatasetCapstoneProject3.xlsx")

In [89]:
df

,CustomerID,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases,Purchased
0,1,23,Male,Mobile,Social Media,5,3,1,0,0
1,2,35,Female,Desktop,Search Engine,12,8,3,2,1
2,3,29,Male,Tablet,Social Media,8,5,2,1,0
3,4,41,Female,Mobile,Email Campaign,15,10,4,3,1
4,5,22,Female,Desktop,Direct,4,2,0,0,0
5,6,38,Male,Desktop,Search Engine,18,11,5,4,1
6,7,30,Male,Mobile,Social Media,7,4,1,1,0
7,8,27,Female,Tablet,Email Campaign,9,6,2,2,1
8,9,45,Male,Desktop,Direct,20,12,5,5,1
9,10,24,Female,Mobile,Social Media,6,3,1,0,0
10,11,36,Male,Tablet,Search Engine,14,9,3,2,1
11,12,31,Female,Desktop,Email Campaign,11,7,2,1,1
12,13,26,Male,Mobile,Direct,5,3,1,0,0
13,14,39,Female,Desktop,Search Engine,16,10,4,3,1
14,15,33,Male,Tablet,Email Campaign,13,8,3,2,1

In [90]:
df.head()

,CustomerID,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases,Purchased
0,1,23,Male,Mobile,Social Media,5,3,1,0,0
1,2,35,Female,Desktop,Search Engine,12,8,3,2,1
2,3,29,Male,Tablet,Social Media,8,5,2,1,0
3,4,41,Female,Mobile,Email Campaign,15,10,4,3,1
4,5,22,Female,Desktop,Direct,4,2,0,0,0

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          15 non-null     int64
 1   Age                 15 non-null     int64
 2   Gender              15 non-null     object
 3   Device              15 non-null     object
 4   Traffic_Source      15 non-null     object
 5   Time_on_Website     15 non-null     int64
 6   Pages_Visited       15 non-null     int64
 7   Ad_Clicks           15 non-null     int64
 8   Previous_Purchases  15 non-null     int64
 9   Purchased           15 non-null     int64
dtypes: int64(7), object(3)
memory usage: 1.3+ KB

In [92]:
X = df.drop(['Purchased','CustomerID'], axis=1)
Y = df['Purchased']

In [93]:
X

,Age,Gender,Device,Traffic_Source,Time_on_Website,Pages_Visited,Ad_Clicks,Previous_Purchases
0,23,Male,Mobile,Social Media,5,3,1,0
1,35,Female,Desktop,Search Engine,12,8,3,2
2,29,Male,Tablet,Social Media,8,5,2,1
3,41,Female,Mobile,Email Campaign,15,10,4,3
4,22,Female,Desktop,Direct,4,2,0,0
5,38,Male,Desktop,Search Engine,18,11,5,4
6,30,Male,Mobile,Social Media,7,4,1,1
7,27,Female,Tablet,Email Campaign,9,6,2,2
8,45,Male,Desktop,Direct,20,12,5,5
9,24,Female,Mobile,Social Media,6,3,1,0
10,36,Male,Tablet,Search Engine,14,9,3,2
11,31,Female,Desktop,Email Campaign,11,7,2,1
12,26,Male,Mobile,Direct,5,3,1,0
13,39,Female,Desktop,Search Engine,16,10,4,3
14,33,Male,Tablet,Email Campaign,13,8,3,2

In [94]:
Y

0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     1
9     0
10    1
11    1
12    0
13    1
14    1
Name: Purchased, dtype: int64

In [95]:
x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42,stratify=Y
)

In [96]:
numerical_features = ['Age','Time_on_Website','Pages_Visited','Ad_Clicks','Previous_Purchases']
categorical_features = ['Gender','Device','Traffic_Source']

In [97]:
numerical_features

['Age', 'Time_on_Website', 'Pages_Visited', 'Ad_Clicks', 'Previous_Purchases']

In [98]:
categorical_features

['Gender', 'Device', 'Traffic_Source']

In [99]:
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown="ignore")

In [100]:
numeric_transformer

StandardScaler()

In [101]:
categorical_transformer

OneHotEncoder(handle_unknown='ignore')

In [102]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features),
    ]
)

preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Age', 'Time_on_Website', 'Pages_Visited',
                                  'Ad_Clicks', 'Previous_Purchases']),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Gender', 'Device', 'Traffic_Source'])])

In [103]:
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", LogisticRegression(max_iter=1000))
    ]
)

pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age', 'Time_on_Website',
                                                   'Pages_Visited', 'Ad_Clicks',
                                                   'Previous_Purchases']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Device',
                                                   'Traffic_Source'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [104]:
# hyperparameter tuning --- GridSearchCV

parameter_grid = {
    "classifier__C": [0.01, 0.1, 1, 10],
    "classifier__penalty": ["l2"],  
    "classifier__solver": ["lbfgs", "saga"]
}

In [105]:
grid_search = GridSearchCV(
    pipeline,
    parameter_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1
)

grid_search.fit(x_train, y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['Age',
                                                                          'Time_on_Website',
                                                                          'Pages_Visited',
                                                                          'Ad_Clicks',
                                                                          'Previous_Purchases']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Gender',
                                                                          'Device',
                                                                          'Traffic_Source'])])),
                                       ('classifier',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid={'classifier__C': [0.01, 0.1, 1, 10],
                         'classifier__penalty': ['l2'],
                         'classifier__solver': ['lbfgs', 'saga']},
             scoring='accuracy')

In [106]:
print("Best Parameters:", grid_search.best_params_)

Best Parameters: {'classifier__C': 1, 'classifier__penalty': 'l2', 'classifier__solver': 'lbfgs'}

In [107]:
y_pred = grid_search.predict(x_test)
print(y_pred)

report = classification_report(y_test, y_pred)
print(report)

print("Accuracy:", accuracy_score(y_test, y_pred))

[0 1 1]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Accuracy: 1.0

In [108]:
# data = pd.DataFrame({
#     'Age':[25],
#     'Gender':['Female'],
#     'Device':['Mobile'],
#     'Traffic_Source':['Social Media'],
#     'Time_on_Website':[5.5],
#     'Pages_Visited':[6],
#     'Ad_Clicks':[2],
#     'Previous_Purchases':[1]
# })



data2 = pd.DataFrame({
    'Age':[20],
    'Gender':['male'],
    'Device':['Mobile'],
    'Traffic_Source':['Social Media'],
    'Time_on_Website':[5.5],
    'Pages_Visited':[6],
    'Ad_Clicks':[9],
    'Previous_Purchases':[1]
})

In [109]:
# prediction = grid_search.predict(data)
# print(prediction)

prediction = grid_search.predict(data2)
print(prediction)

[1]

In [110]:
if prediction == 1:
   print("Show personalized product recommendations\nOffer targeted discounts\nSend marketing emails")
else:
    print("Avoid unnecessary ads\nReduce marketing cost\nFocus on high-value customers")

Show personalized product recommendations
Offer targeted discounts
Send marketing emails